/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package blister_pack.blister;

public final class R {
    public static final class array {
        public static final int extra_params=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f050001;
        public static final int green=0x7f050002;
        public static final int red=0x7f050000;
        public static final int white=0x7f050003;
    }
    public static final class drawable {
        public static final int cross=0x7f020000;
        public static final int drug_basket=0x7f020001;
        public static final int ic_menu_add=0x7f020002;
        public static final int ic_menu_agenda=0x7f020003;
        public static final int ic_menu_close=0x7f020004;
        public static final int ic_menu_delete=0x7f020005;
        public static final int ic_menu_help=0x7f020006;
        public static final int medical_pot_pills=0x7f020007;
        public static final int menuitem_background=0x7f020008;
        public static final int menuitem_background_focus=0x7f020009;
        public static final int menuitem_background_pressed=0x7f02000a;
        public static final int pills_4=0x7f02000b;
        public static final int pills_5=0x7f02000c;
        public static final int pills_case=0x7f02000d;
        public static final int pills_clock=0x7f02000e;
        public static final int pills_man=0x7f02000f;
        public static final int rectangle=0x7f020010;
        public static final int settings_header_raw=0x7f020011;
        public static final int shield=0x7f020012;
        public static final int timepicker_down_btn=0x7f020013;
        public static final int timepicker_down_disabled=0x7f020014;
        public static final int timepicker_down_disabled_focused=0x7f020015;
        public static final int timepicker_down_normal=0x7f020016;
        public static final int timepicker_down_pressed=0x7f020017;
        public static final int timepicker_down_selected=0x7f020018;
        public static final int timepicker_input=0x7f020019;
        public static final int timepicker_input_disabled=0x7f02001a;
        public static final int timepicker_input_normal=0x7f02001b;
        public static final int timepicker_input_pressed=0x7f02001c;
        public static final int timepicker_input_selected=0x7f02001d;
        public static final int timepicker_up_btn=0x7f02001e;
        public static final int timepicker_up_disabled=0x7f02001f;
        public static final int timepicker_up_disabled_focused=0x7f020020;
        public static final int timepicker_up_normal=0x7f020021;
        public static final int timepicker_up_pressed=0x7f020022;
        public static final int timepicker_up_selected=0x7f020023;
        public static final int top_bar=0x7f020024;
    }
    public static final class id {
        public static final int AddDirectTimeLayout=0x7f080013;
        public static final int AddDirectTimeTimePicker=0x7f080014;
        public static final int AddRelTimeButtonLayout=0x7f080010;
        public static final int AddRelTimeButtonPanel=0x7f08000f;
        public static final int AddRelTimeCancelButton=0x7f080012;
        public static final int AddRelTimeEveryLayout=0x7f080003;
        public static final int AddRelTimeEverySetPanel=0x7f080006;
        public static final int AddRelTimeEveryText=0x7f080005;
        public static final int AddRelTimeEveryTitle=0x7f080004;
        public static final int AddRelTimeFromLayout=0x7f080007;
        public static final int AddRelTimeFromSetPanel=0x7f08000a;
        public static final int AddRelTimeFromText=0x7f080009;
        public static final int AddRelTimeFromTitle=0x7f080008;
        public static final int AddRelTimeLayout=0x7f080002;
        public static final int AddRelTimeOkButton=0x7f080011;
        public static final int AddRelTimeScrollView=0x7f080001;
        public static final int AddRelTimeToLayout=0x7f08000b;
        public static final int AddRelTimeToSetPanel=0x7f08000e;
        public static final int AddRelTimeToText=0x7f08000d;
        public static final int AddRelTimeToTitle=0x7f08000c;
        public static final int AddRelTimeWindowLayout=0x7f080000;
        public static final int ListWindowBottomButtonLayout=0x7f08005e;
        public static final int ListWindowBottomButtonPanel=0x7f08005d;
        public static final int ListWindowEmptyListAddButton1=0x7f08005b;
        public static final int ListWindowEmptyListAddButton2=0x7f08005c;
        public static final int ListWindowEmptyListLayout=0x7f080059;
        public static final int ListWindowEmptyListText=0x7f08005a;
        public static final int ListWindowImage=0x7f080055;
        public static final int ListWindowImageLayout=0x7f080054;
        public static final int ListWindowListLayout=0x7f080058;
        public static final int ListWindowMainLayout=0x7f080052;
        public static final int ListWindowOKButton=0x7f08005f;
        public static final int ListWindowText=0x7f080057;
        public static final int ListWindowTextLayout=0x7f080056;
        public static final int ListWindowTopPanel=0x7f080053;
        public static final int PickerEditText=0x7f080062;
        public static final int PickerLayout=0x7f080060;
        public static final int PickerMinusButton=0x7f080063;
        public static final int PickerPlusButton=0x7f080061;
        public static final int addTimetableButtonLayout=0x7f080023;
        public static final int addTimetableButtonPanel=0x7f080022;
        public static final int addTimetableCancelButton=0x7f080025;
        public static final int addTimetableDaysText=0x7f080021;
        public static final int addTimetableDivider=0x7f080028;
        public static final int addTimetableLayout=0x7f080016;
        public static final int addTimetableListItemText=0x7f080015;
        public static final int addTimetableNumberLayout=0x7f08001d;
        public static final int addTimetableNumberSetButton=0x7f080020;
        public static final int addTimetableNumberSubLayout=0x7f08001e;
        public static final int addTimetableNumberText=0x7f08001c;
        public static final int addTimetableNumberValueLayout=0x7f080029;
        public static final int addTimetableNumberValueText=0x7f08001f;
        public static final int addTimetableOkButton=0x7f080024;
        public static final int addTimetableParamsLayout=0x7f080026;
        public static final int addTimetableTimeLayout=0x7f080018;
        public static final int addTimetableTimeSetButton=0x7f08001b;
        public static final int addTimetableTimeSubLayout=0x7f080019;
        public static final int addTimetableTimeText=0x7f080017;
        public static final int addTimetableTimeValueLayout=0x7f080027;
        public static final int addTimetableTimeValueText=0x7f08001a;
        public static final int basicListItemLayout=0x7f08002a;
        public static final int basicListItemStat=0x7f08002e;
        public static final int basicListItemStatLayout=0x7f08002d;
        public static final int basicListItemTitle=0x7f08002c;
        public static final int basicListItemTitleLayout=0x7f08002b;
        public static final int confirmActivityButtonLayout=0x7f080033;
        public static final int confirmActivityButtonPanel=0x7f080032;
        public static final int confirmActivityConfirmButton=0x7f080034;
        public static final int confirmActivityIgnoreButton=0x7f080035;
        public static final int confirmActivityLayout=0x7f08002f;
        public static final int confirmActivityNameText=0x7f080030;
        public static final int confirmActivityStatText=0x7f080031;
        public static final int editScheduleBottomButtonLayout=0x7f08004f;
        public static final int editScheduleBottomButtonPanel=0x7f08004e;
        public static final int editScheduleCancelButton=0x7f080051;
        public static final int editScheduleDataLayout=0x7f08003c;
        public static final int editScheduleDataPanel=0x7f08003d;
        public static final int editScheduleEditName=0x7f080041;
        public static final int editScheduleEditNameLayout=0x7f080040;
        public static final int editScheduleImage=0x7f080039;
        public static final int editScheduleImageLayout=0x7f080038;
        public static final int editScheduleMainLayout=0x7f080036;
        public static final int editScheduleNameLayout=0x7f08003e;
        public static final int editScheduleNameText=0x7f08003f;
        public static final int editScheduleOKButton=0x7f080050;
        public static final int editScheduleParamsLayout=0x7f080042;
        public static final int editScheduleParamsText=0x7f080043;
        public static final int editScheduleSetButton=0x7f08004d;
        public static final int editScheduleSetParamsLayout=0x7f080044;
        public static final int editScheduleSetParamsPanel=0x7f080045;
        public static final int editScheduleSpinner=0x7f080046;
        public static final int editScheduleText=0x7f08003b;
        public static final int editScheduleTextLayout=0x7f08003a;
        public static final int editScheduleTopPanel=0x7f080037;
        public static final int editScheduleValueDimText=0x7f08004c;
        public static final int editScheduleValueLayout=0x7f080047;
        public static final int editScheduleValueSubLayout=0x7f080048;
        public static final int editScheduleValueText=0x7f08004b;
        public static final int editScheduleValueTextLayout=0x7f080049;
        public static final int editScheduleValueTitle=0x7f08004a;
        public static final int group01=0x7f08007f;
        public static final int group02=0x7f08007c;
        public static final int infoDeleteItem=0x7f080074;
        public static final int mainAboutItem=0x7f08006f;
        public static final int mainAddItem=0x7f08006d;
        public static final int mainClearItem=0x7f08006e;
        public static final int mainContextDeleteItem=0x7f08006b;
        public static final int mainContextEditItem=0x7f08006c;
        public static final int missedConfirmAll=0x7f080072;
        public static final int missedContextConfirmItem=0x7f080070;
        public static final int missedContextIgnoreItem=0x7f080071;
        public static final int missedIgnoreAll=0x7f080073;
        public static final int setTimeAddDirectItem=0x7f080077;
        public static final int setTimeAddRelativeItem=0x7f080078;
        public static final int setTimeContextDeleteItem=0x7f080075;
        public static final int setTimeContextEditItem=0x7f080076;
        public static final int setTimeDeleteAllItem=0x7f080079;
        public static final int setValueLayout=0x7f080064;
        public static final int setValuePicker=0x7f080065;
        public static final int weekAddItem=0x7f08007d;
        public static final int weekClearItem=0x7f08007e;
        public static final int weekContextDeleteItem=0x7f08007a;
        public static final int weekContextEditItem=0x7f08007b;
        public static final int weekDeleteItem=0x7f080080;
        public static final int weekListItemLayout=0x7f080066;
        public static final int weekListItemStat=0x7f08006a;
        public static final int weekListItemStatLayout=0x7f080069;
        public static final int weekListItemTitle=0x7f080068;
        public static final int weekListItemTitleLayout=0x7f080067;
    }
    public static final class layout {
        public static final int add_rel_time_window=0x7f030000;
        public static final int add_time_layout=0x7f030001;
        public static final int add_timetable_list_item=0x7f030002;
        public static final int add_timetable_window=0x7f030003;
        public static final int add_timetable_window_vertical=0x7f030004;
        public static final int basic_list_item=0x7f030005;
        public static final int confirm_activity=0x7f030006;
        public static final int edit_schedule_window=0x7f030007;
        public static final int edit_schedule_window_vertical=0x7f030008;
        public static final int gradient_drawable=0x7f030009;
        public static final int list_window=0x7f03000a;
        public static final int picker_layout=0x7f03000b;
        public static final int set_value_layout=0x7f03000c;
        public static final int week_list_item=0x7f03000d;
    }
    public static final class menu {
        public static final int main_window_context_menu=0x7f070000;
        public static final int main_window_menu=0x7f070001;
        public static final int missed_notifications_window_context_menu=0x7f070002;
        public static final int missed_notifications_window_menu=0x7f070003;
        public static final int schedule_info_window_menu=0x7f070004;
        public static final int set_time_window_context_menu=0x7f070005;
        public static final int set_time_window_menu=0x7f070006;
        public static final int week_window_context_menu=0x7f070007;
        public static final int week_window_menu=0x7f070008;
    }
    public static final class string {
        public static final int Friday=0x7f060004;
        /**  Days of week 
         */
        public static final int Monday=0x7f060000;
        public static final int Saturday=0x7f060005;
        public static final int Sunday=0x7f060006;
        public static final int Thursday=0x7f060003;
        public static final int Tuesday=0x7f060001;
        public static final int Wednesday=0x7f060002;
        /**  Button/item texts 
         */
        public static final int about_text=0x7f06001e;
        public static final int add_text=0x7f06001f;
        public static final int add_time_series_text=0x7f060020;
        public static final int add_time_text=0x7f060021;
        /**  Dialog/notification messages 
         */
        public static final int add_timetable_no_data_message=0x7f06000e;
        public static final int cancel_text=0x7f060022;
        public static final int choose_parameter_text=0x7f060023;
        public static final int clear_all_dialog_message=0x7f06000f;
        public static final int clear_all_text=0x7f060024;
        public static final int clear_day_dialog_message=0x7f060010;
        public static final int clear_text=0x7f060025;
        public static final int clear_timetable_text=0x7f060026;
        public static final int close_text=0x7f060027;
        public static final int confirm_all_dialog_message=0x7f060011;
        public static final int confirm_all_text=0x7f060028;
        public static final int confirm_text=0x7f060029;
        public static final int confirmed_text=0x7f06002a;
        public static final int course_ended_text=0x7f06002b;
        public static final int course_parameters_text=0x7f06002c;
        public static final int data_not_typed_dialog_message=0x7f060012;
        public static final int day_text_low=0x7f06002d;
        public static final int days_remained_text=0x7f06002e;
        public static final int days_text=0x7f06002f;
        public static final int days_text_low=0x7f060030;
        public static final int del_text=0x7f060031;
        public static final int delete_all_text=0x7f060032;
        public static final int delete_course_dialog_message=0x7f060013;
        public static final int delete_course_text=0x7f060033;
        public static final int delete_item_dialog_message=0x7f060014;
        public static final int delete_text=0x7f060034;
        public static final int discard_text=0x7f060035;
        public static final int duration_of_course_text=0x7f060036;
        public static final int duration_text=0x7f060037;
        public static final int edit_schedule_window_title=0x7f060008;
        public static final int edit_text=0x7f060038;
        public static final int end_time_text=0x7f060039;
        public static final int ignore_all_dialog_message=0x7f060015;
        public static final int ignore_all_text=0x7f06003a;
        public static final int ignore_text=0x7f06003b;
        public static final int ignored_text=0x7f06003c;
        public static final int incorrect_data_dialog_message=0x7f060016;
        public static final int info_text_low=0x7f06003d;
        /**  Empty list messages 
         */
        public static final int list_is_empty_message=0x7f06000a;
        /**  Window titles 
         */
        public static final int main_window_title=0x7f060007;
        public static final int missed_notification_message=0x7f060017;
        public static final int missed_notification_title=0x7f060018;
        public static final int missed_notifications_list_is_empty=0x7f06000b;
        public static final int missed_notifications_window_title=0x7f060009;
        public static final int name_already_exists_dialog_message=0x7f060019;
        public static final int name_not_typed_dialog_message=0x7f06001a;
        public static final int name_text=0x7f06003e;
        public static final int notification_message=0x7f06001b;
        public static final int notification_title=0x7f06001c;
        public static final int number_of_pills_text=0x7f06003f;
        /**  Presets 
         */
        public static final int number_preset=0x7f06004f;
        public static final int ok_text=0x7f060040;
        public static final int pills_remained_text=0x7f060041;
        public static final int pills_taken_text=0x7f060042;
        public static final int pills_text=0x7f060043;
        public static final int pills_to_take_text=0x7f060044;
        public static final int save_text=0x7f060045;
        public static final int saved_message=0x7f060046;
        public static final int schedules_list_is_empty=0x7f06000c;
        public static final int set_number_of_pills_text=0x7f060047;
        public static final int set_text=0x7f060048;
        public static final int set_value_text=0x7f060049;
        public static final int start_time_text=0x7f06004a;
        public static final int temporarily_unavailable_message=0x7f06001d;
        public static final int time_interval_text=0x7f06004b;
        public static final int time_preset=0x7f060050;
        public static final int time_text=0x7f06004c;
        public static final int times_list_is_empty=0x7f06000d;
        public static final int timetable_text_low=0x7f06004d;
        public static final int value_text=0x7f06004e;
    }
}
